-- us_equity_bar 的 delta 回看窗 NULL → 7 (纯 seed UPDATE, 无 DDL / 无破坏性变更 ⇒ 单 PR 合规
-- per .claude/rules/migration-rules.md §2)。
--
-- 🚨 本 migration **推翻** 20260801_2248 尾部「蓄意留 NULL」清单里的**一项**, 且只推翻这一项 ——
-- eod_bar / short_selling / volatility / fundamental / 报告期语义类 / 覆盖式 upsert 类**一律不动**。
-- 原文给了两条理由, 逐条复核:
--
--   ① 「2026-08-01 实测数据年龄均为 1 天 (上个交易日), 单日窗在这些端点上验证正常」
--      → **仍然成立**。2026-08-02 复测: 在采的 12 只 us 标的, daily_bar 的 max(trade_date)
--      全部 = 2026-07-31 (上个交易日)。但它证的是「正常时窗口是对的」, **不是**「漏跑时能自愈」
--      —— 这两件事不能互相替代。
--
--   ② 「且是全仓最大的几张表, 无证据的加宽只换来每晚成倍的重复行去重开销」
--      → **对 us_equity_bar 不成立**。这是本次改判的唯一新输入: 原文把它与 eod_bar / fundamental
--      按「日线 / 大表」归为一类给理由, 但两者工作集差着量级 ——
--        · eod_bar         = cn/hk 全量 **2782 只**
--        · us_equity_bar   = **成员制**, 受 Instrument.need_sync 采集闸约束, 当前 **12 只**
--                            (= optionsdesk 锚表 12 条; 19,465 只在库 us 标的里只开 12)
--      加宽到 7 天 ⇒ 每晚多约 84 行进 createMany(skipDuplicates) 去重, 可忽略。
--      且 `request_history_kline` 是**区间接口**: 拉 7 天与拉 1 天同为 1 次请求 / 1 份历史 K 线
--      额度 (E9 额度模型) ⇒ vendor 侧零增量。
--
-- 为什么值得买这份保险 —— 性质与 F9 那 6 个维度**不同**, 不要混为一谈:
--   · F9 的 6 个是**结构性必漏** (T+1 披露 / 周更 cron 配精确当日窗 ⇒ 单日窗**永远**取不到),
--     那是在修已发生的 bug;
--   · 日线是 **T+0**, 精确当日窗**平时是对的**, 只在「漏跑一整轮」时开洞。而漏跑**无补偿**:
--     misfire_policy='fire-now' 的语义是「补触发, 但 asOf 取自 now」(sync-tick-driver.ts:21
--     明写「misfire ≠ backfill」) ⇒ 被跳过的那个业务日**再没有任何一次请求会问起**, 缺口永久
--     且完全静默 —— 表级探针判的是**数据年龄**, 抓得到「卡住」, 抓不到中段单日洞。
--   · retry_max=3 只覆盖同一 tick 窗内的瞬时失败, 覆盖不了跨 us 业务日翻转点的停机。
--   · 而这张表正是 045 雷达距 W% / M2a 区间时序图 + RV21 的直接供给方, 洞会一路传导到决策面。
--
-- 取值 7 = 直接套 20260801_2248 的定值规则日频档, **不新造参数**。日线披露滞后为 0, 这 7 天
-- 纯粹是留给「漏跑追赶」的自愈窗 (规则原文的 N ≥ 披露滞后 + tick 间隔, 此处 = 0 + 1, 7 远够)。
--
-- ⚠️ eod_bar (cn/hk 日线) 是**同款形态但本次刻意不动**: 它工作集 2782 只, 而设了回看窗会让
-- deltaCursorUsable() 返 false ⇒ 关掉「已落当日行则跳过」游标、每晚全工作集重取。这是真实的
-- 成本变化 (不是本条那种 ≈0), 必须先量一晚 —— 现在游标跳掉多少只 / 关掉后请求量与窗口时长
-- 各变多少 —— 再定。**无实测不改**, 这正是 20260801_2248 第 ② 条理由在它身上仍然成立的地方。
--
-- 幂等: 重跑同值覆盖零变更。未列出的维度逐行零影响。
-- migration_refs: specs/045-optionsdesk-anchors-radar (T012 投影链的上游供给)
--   + docs/plans/2026-07/07-30-sellput-viz-p3b-data-architecture.md §9-F9。

UPDATE "marketdata"."sync_dimension" SET "delta_lookback_days" = 7
 WHERE "dimension_key" = 'us_equity_bar';
